# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.open_folder = QtWidgets.QPushButton(self.centralwidget)
        self.open_folder.setGeometry(QtCore.QRect(10, 10, 121, 41))
        self.open_folder.setObjectName("open_folder")
        self.list_image = QtWidgets.QListWidget(self.centralwidget)
        self.list_image.setGeometry(QtCore.QRect(10, 60, 161, 491))
        self.list_image.setObjectName("list_image")
        self.rotate_left = QtWidgets.QPushButton(self.centralwidget)
        self.rotate_left.setGeometry(QtCore.QRect(180, 510, 101, 41))
        self.rotate_left.setObjectName("rotate_left")
        self.rotate_right = QtWidgets.QPushButton(self.centralwidget)
        self.rotate_right.setGeometry(QtCore.QRect(290, 510, 101, 41))
        self.rotate_right.setObjectName("rotate_right")
        self.mirror_image = QtWidgets.QPushButton(self.centralwidget)
        self.mirror_image.setGeometry(QtCore.QRect(400, 510, 101, 41))
        self.mirror_image.setObjectName("mirror_image")
        self.sharpness_image = QtWidgets.QPushButton(self.centralwidget)
        self.sharpness_image.setGeometry(QtCore.QRect(510, 510, 101, 41))
        self.sharpness_image.setObjectName("sharpness_image")
        self.black_white = QtWidgets.QPushButton(self.centralwidget)
        self.black_white.setGeometry(QtCore.QRect(620, 510, 101, 41))
        self.black_white.setObjectName("black_white")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(190, 273, 51, 20))
        self.image.setObjectName("image")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EazyEditor"))
        self.open_folder.setText(_translate("MainWindow", "Папка"))
        self.rotate_left.setText(_translate("MainWindow", "Вліво "))
        self.rotate_right.setText(_translate("MainWindow", "Вправо"))
        self.mirror_image.setText(_translate("MainWindow", "Дзеркало"))
        self.sharpness_image.setText(_translate("MainWindow", "Різкість"))
        self.black_white.setText(_translate("MainWindow", "Ч /  Б"))
        self.image.setText(_translate("MainWindow", "Картинка"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
